# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: virus-pipe-1.3
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - samtools=1.14
  - bcftools=1.14
  - htslib=1.14
  - mosdepth=0.2.9
  - r-base=3.6.1
  - r-tidyverse=1.3.0
  - perl-pdf-api2
  - perl-pdf-table=0.11.0
  - snpeff=5.0.0
  - bwa=0.7.17
  - perl-excel-writer-xlsx
  - perl-json=4.05
  - perl-json-parse=0.61
  - perl-rest-client=281
